/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SovaKeyShop } from "./SovaKeyShop";
export * as factories from "./factories";
export { SovaKeyShop__factory } from "./factories/SovaKeyShop__factory";
