/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SovaJackpot {
  export type JackpotResultStruct = {
    player: AddressLike;
    tier: BigNumberish;
    floor: BigNumberish;
    timestamp: BigNumberish;
  };

  export type JackpotResultStructOutput = [
    player: string,
    tier: bigint,
    floor: bigint,
    timestamp: bigint
  ] & { player: string; tier: bigint; floor: bigint; timestamp: bigint };
}

export interface SovaJackpotInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIER_MAJOR"
      | "TIER_MEGA"
      | "TIER_MINOR"
      | "TIER_NONE"
      | "getResult"
      | "majorThreshold"
      | "minorThreshold"
      | "owner"
      | "previewTier"
      | "results"
      | "rollJackpot"
      | "setSigner"
      | "setThresholds"
      | "signer"
      | "transferOwnership"
      | "usedSeeds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JackpotRolled"
      | "SignerUpdated"
      | "ThresholdsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TIER_MAJOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER_MEGA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIER_MINOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER_NONE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "majorThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minorThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewTier",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "results", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "rollJackpot",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setThresholds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "signer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedSeeds",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "TIER_MAJOR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIER_MEGA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIER_MINOR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIER_NONE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "majorThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minorThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rollJackpot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedSeeds", data: BytesLike): Result;
}

export namespace JackpotRolledEvent {
  export type InputTuple = [
    player: AddressLike,
    seedHash: BytesLike,
    tier: BigNumberish,
    floor: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    seedHash: string,
    tier: bigint,
    floor: bigint
  ];
  export interface OutputObject {
    player: string;
    seedHash: string;
    tier: bigint;
    floor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerUpdatedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsUpdatedEvent {
  export type InputTuple = [minor: BigNumberish, major: BigNumberish];
  export type OutputTuple = [minor: bigint, major: bigint];
  export interface OutputObject {
    minor: bigint;
    major: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SovaJackpot extends BaseContract {
  connect(runner?: ContractRunner | null): SovaJackpot;
  waitForDeployment(): Promise<this>;

  interface: SovaJackpotInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIER_MAJOR: TypedContractMethod<[], [bigint], "view">;

  TIER_MEGA: TypedContractMethod<[], [bigint], "view">;

  TIER_MINOR: TypedContractMethod<[], [bigint], "view">;

  TIER_NONE: TypedContractMethod<[], [bigint], "view">;

  getResult: TypedContractMethod<
    [seedHash: BytesLike],
    [SovaJackpot.JackpotResultStructOutput],
    "view"
  >;

  majorThreshold: TypedContractMethod<[], [bigint], "view">;

  minorThreshold: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  previewTier: TypedContractMethod<
    [seed: BytesLike, player: AddressLike],
    [bigint],
    "view"
  >;

  results: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        player: string;
        tier: bigint;
        floor: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  rollJackpot: TypedContractMethod<
    [seed: BytesLike, floor: BigNumberish, signature: BytesLike],
    [bigint],
    "nonpayable"
  >;

  setSigner: TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;

  setThresholds: TypedContractMethod<
    [_minor: BigNumberish, _major: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedSeeds: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIER_MAJOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_MEGA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_MINOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [seedHash: BytesLike],
    [SovaJackpot.JackpotResultStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "majorThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minorThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewTier"
  ): TypedContractMethod<
    [seed: BytesLike, player: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        player: string;
        tier: bigint;
        floor: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rollJackpot"
  ): TypedContractMethod<
    [seed: BytesLike, floor: BigNumberish, signature: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSigner"
  ): TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setThresholds"
  ): TypedContractMethod<
    [_minor: BigNumberish, _major: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedSeeds"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "JackpotRolled"
  ): TypedContractEvent<
    JackpotRolledEvent.InputTuple,
    JackpotRolledEvent.OutputTuple,
    JackpotRolledEvent.OutputObject
  >;
  getEvent(
    key: "SignerUpdated"
  ): TypedContractEvent<
    SignerUpdatedEvent.InputTuple,
    SignerUpdatedEvent.OutputTuple,
    SignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsUpdated"
  ): TypedContractEvent<
    ThresholdsUpdatedEvent.InputTuple,
    ThresholdsUpdatedEvent.OutputTuple,
    ThresholdsUpdatedEvent.OutputObject
  >;

  filters: {
    "JackpotRolled(address,bytes32,uint256,uint256)": TypedContractEvent<
      JackpotRolledEvent.InputTuple,
      JackpotRolledEvent.OutputTuple,
      JackpotRolledEvent.OutputObject
    >;
    JackpotRolled: TypedContractEvent<
      JackpotRolledEvent.InputTuple,
      JackpotRolledEvent.OutputTuple,
      JackpotRolledEvent.OutputObject
    >;

    "SignerUpdated(address,address)": TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;
    SignerUpdated: TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;

    "ThresholdsUpdated(uint256,uint256)": TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
    ThresholdsUpdated: TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
  };
}
