/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SovaKeyShopInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyKeys"
      | "keyPrice"
      | "owner"
      | "setKeyPrice"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "KeyPriceUpdated" | "KeysPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "keyPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setKeyPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buyKeys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keyPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setKeyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace KeyPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeysPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    quantity: BigNumberish,
    totalPaid: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    quantity: bigint,
    totalPaid: bigint
  ];
  export interface OutputObject {
    buyer: string;
    quantity: bigint;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SovaKeyShop extends BaseContract {
  connect(runner?: ContractRunner | null): SovaKeyShop;
  waitForDeployment(): Promise<this>;

  interface: SovaKeyShopInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyKeys: TypedContractMethod<[quantity: BigNumberish], [void], "payable">;

  keyPrice: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setKeyPrice: TypedContractMethod<
    [_newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyKeys"
  ): TypedContractMethod<[quantity: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "keyPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setKeyPrice"
  ): TypedContractMethod<[_newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "KeyPriceUpdated"
  ): TypedContractEvent<
    KeyPriceUpdatedEvent.InputTuple,
    KeyPriceUpdatedEvent.OutputTuple,
    KeyPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "KeysPurchased"
  ): TypedContractEvent<
    KeysPurchasedEvent.InputTuple,
    KeysPurchasedEvent.OutputTuple,
    KeysPurchasedEvent.OutputObject
  >;

  filters: {
    "KeyPriceUpdated(uint256,uint256)": TypedContractEvent<
      KeyPriceUpdatedEvent.InputTuple,
      KeyPriceUpdatedEvent.OutputTuple,
      KeyPriceUpdatedEvent.OutputObject
    >;
    KeyPriceUpdated: TypedContractEvent<
      KeyPriceUpdatedEvent.InputTuple,
      KeyPriceUpdatedEvent.OutputTuple,
      KeyPriceUpdatedEvent.OutputObject
    >;

    "KeysPurchased(address,uint256,uint256)": TypedContractEvent<
      KeysPurchasedEvent.InputTuple,
      KeysPurchasedEvent.OutputTuple,
      KeysPurchasedEvent.OutputObject
    >;
    KeysPurchased: TypedContractEvent<
      KeysPurchasedEvent.InputTuple,
      KeysPurchasedEvent.OutputTuple,
      KeysPurchasedEvent.OutputObject
    >;
  };
}
