/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SovaSplitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "jackpotContract"
      | "jackpotShare"
      | "owner"
      | "setAddresses"
      | "setShares"
      | "teamShare"
      | "teamWallet"
      | "weeklyPoolContract"
      | "weeklyShare"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Split"): EventFragment;

  encodeFunctionData(
    functionFragment: "jackpotContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "jackpotShare",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAddresses",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setShares",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "teamShare", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "teamWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "weeklyPoolContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "weeklyShare",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "jackpotContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jackpotShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "teamShare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "teamWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "weeklyPoolContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "weeklyShare",
    data: BytesLike
  ): Result;
}

export namespace SplitEvent {
  export type InputTuple = [
    total: BigNumberish,
    toJackpot: BigNumberish,
    toWeekly: BigNumberish,
    toTeam: BigNumberish
  ];
  export type OutputTuple = [
    total: bigint,
    toJackpot: bigint,
    toWeekly: bigint,
    toTeam: bigint
  ];
  export interface OutputObject {
    total: bigint;
    toJackpot: bigint;
    toWeekly: bigint;
    toTeam: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SovaSplitter extends BaseContract {
  connect(runner?: ContractRunner | null): SovaSplitter;
  waitForDeployment(): Promise<this>;

  interface: SovaSplitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  jackpotContract: TypedContractMethod<[], [string], "view">;

  jackpotShare: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setAddresses: TypedContractMethod<
    [_jackpot: AddressLike, _weeklyPool: AddressLike, _teamWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setShares: TypedContractMethod<
    [_jackpot: BigNumberish, _weekly: BigNumberish, _team: BigNumberish],
    [void],
    "nonpayable"
  >;

  teamShare: TypedContractMethod<[], [bigint], "view">;

  teamWallet: TypedContractMethod<[], [string], "view">;

  weeklyPoolContract: TypedContractMethod<[], [string], "view">;

  weeklyShare: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "jackpotContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "jackpotShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAddresses"
  ): TypedContractMethod<
    [_jackpot: AddressLike, _weeklyPool: AddressLike, _teamWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setShares"
  ): TypedContractMethod<
    [_jackpot: BigNumberish, _weekly: BigNumberish, _team: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "teamShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "teamWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "weeklyPoolContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "weeklyShare"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Split"
  ): TypedContractEvent<
    SplitEvent.InputTuple,
    SplitEvent.OutputTuple,
    SplitEvent.OutputObject
  >;

  filters: {
    "Split(uint256,uint256,uint256,uint256)": TypedContractEvent<
      SplitEvent.InputTuple,
      SplitEvent.OutputTuple,
      SplitEvent.OutputObject
    >;
    Split: TypedContractEvent<
      SplitEvent.InputTuple,
      SplitEvent.OutputTuple,
      SplitEvent.OutputObject
    >;
  };
}
