/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SovaJackpotPrizeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimJackpot"
      | "claimed"
      | "getBalance"
      | "owner"
      | "setSigner"
      | "signer"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "JackpotClaimed"): EventFragment;

  encodeFunctionData(
    functionFragment: "claimJackpot",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "signer", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "claimJackpot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setSigner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signer", data: BytesLike): Result;
}

export namespace JackpotClaimedEvent {
  export type InputTuple = [
    player: AddressLike,
    requestId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [player: string, requestId: bigint, amount: bigint];
  export interface OutputObject {
    player: string;
    requestId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SovaJackpotPrize extends BaseContract {
  connect(runner?: ContractRunner | null): SovaJackpotPrize;
  waitForDeployment(): Promise<this>;

  interface: SovaJackpotPrizeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimJackpot: TypedContractMethod<
    [requestId: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setSigner: TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimJackpot"
  ): TypedContractMethod<
    [requestId: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSigner"
  ): TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "JackpotClaimed"
  ): TypedContractEvent<
    JackpotClaimedEvent.InputTuple,
    JackpotClaimedEvent.OutputTuple,
    JackpotClaimedEvent.OutputObject
  >;

  filters: {
    "JackpotClaimed(address,uint256,uint256)": TypedContractEvent<
      JackpotClaimedEvent.InputTuple,
      JackpotClaimedEvent.OutputTuple,
      JackpotClaimedEvent.OutputObject
    >;
    JackpotClaimed: TypedContractEvent<
      JackpotClaimedEvent.InputTuple,
      JackpotClaimedEvent.OutputTuple,
      JackpotClaimedEvent.OutputObject
    >;
  };
}
